all:
  editable_content:

    # class used to render the editable content areas
    content_service_class: ioEditableContentService

    content_service_options:
      empty_text:         "[Click to edit]"         # this content will be shown in place of empty content
      edit_mode:          fancybox                  # The default editor mode: fancybox|inline
      admin_credential:   false    # inline editing only made available to users with this credential
      editable_class_name: io_editable_content

    assets_web_root:     /ioEditableContentPlugin

    # whether or not to automatically include the following asset libraries
    load_fancybox:        true
    load_jquery:          true
    load_jquery_metadata: true
    load_jquery_ui:       true